# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('noRef', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Référence Article')),
                ('nom', models.CharField(max_length=30, verbose_name="Nom de l'article")),
                ('prixHT', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Prix HT')),
                ('is_taxes', models.BooleanField(default=True, verbose_name='Taxes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('idMembre', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Numéro de membre')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prénom')),
                ('courriel', models.EmailField(max_length=50, unique=True, verbose_name='Courriel')),
                ('cp', models.CharField(max_length=7, verbose_name='Code Postal')),
                ('telephone', models.CharField(max_length=12, verbose_name='Numéro de téléphone')),
                ('dateAdh', models.DateField(verbose_name="Date d'Adhésion")),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tps', models.DecimalField(decimal_places=4, max_digits=5)),
                ('tvq', models.DecimalField(decimal_places=4, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noTrans', models.CharField(help_text="20170506004 si c'est la 4ème vente de la journée du 6 mai 2017 par exemple", max_length=11, verbose_name='Numréro de transaction')),
                ('moyenPaiement', models.CharField(choices=[('DEBIT', 'Débit'), ('COMPTANT', 'Comptant'), ('LIGNE', 'En ligne')], max_length=10, verbose_name='Moyen de Paiement')),
                ('dateTrans', models.DateTimeField(auto_now_add=True, verbose_name='Date de transaction')),
                ('vendeur', models.CharField(max_length=30)),
                ('payee', models.BooleanField(default=False, verbose_name='Taxes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Membre')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('noVente', models.CharField(help_text="rajouter le numero d'item de la transaction au numero de transaction", max_length=13, primary_key=True, serialize=False, verbose_name='Numéro de vente')),
                ('prixHTVendu', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Prix de vente HT')),
            ],
        ),
        migrations.CreateModel(
            name='AbonnementAtelier',
            fields=[
                ('duree', models.DurationField(choices=[(datetime.timedelta(0, 14400), 'Soir'), (datetime.timedelta(1), 'Journée'), (datetime.timedelta(7), 'Semaine'), (datetime.timedelta(31), 'Mois'), (datetime.timedelta(365), 'Année')], verbose_name='Durée')),
                ('item_ptr', models.OneToOneField(default=datetime.datetime(2017, 5, 25, 22, 8, 48, 896236), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item')),
            ],
            bases=('ventes.item',),
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('item_ptr', models.OneToOneField(default=datetime.datetime(2017, 5, 25, 22, 8, 48, 898996), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item')),
            ],
            bases=('ventes.item',),
        ),
        migrations.CreateModel(
            name='ContributionVolontaire',
            fields=[
                ('item_ptr', models.OneToOneField(default=datetime.datetime(2017, 5, 25, 22, 8, 48, 898229), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item')),
            ],
            bases=('ventes.item',),
        ),
        migrations.CreateModel(
            name='Entreposage',
            fields=[
                ('duree', models.DurationField(choices=[(datetime.timedelta(1), 'Journée'), (datetime.timedelta(7), 'Semaine'), (datetime.timedelta(31), 'Mois')], verbose_name='Durée')),
                ('taille', models.CharField(choices=[('petit', '2*3'), ('moyen', '4*3'), ('grand', '8*3')], max_length=10, verbose_name='Taille')),
                ('item_ptr', models.OneToOneField(default=datetime.datetime(2017, 5, 25, 22, 8, 48, 897417), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item')),
            ],
            bases=('ventes.item',),
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('date', models.DateField(verbose_name='Date de la formation')),
                ('formateur', models.CharField(max_length=30, verbose_name='Formateur')),
                ('cout', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Coût')),
                ('jauge', models.IntegerField(verbose_name='Jauge')),
                ('duree', models.DurationField(verbose_name='Durée')),
                ('item_ptr', models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item')),
            ],
            bases=('ventes.item',),
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('item_ptr', models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item')),
            ],
            bases=('ventes.item',),
        ),
        migrations.AddField(
            model_name='vente',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Item'),
        ),
        migrations.AddField(
            model_name='vente',
            name='noTrans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Transaction'),
        ),
    ]
