# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_auto_20170525_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prénom')),
                ('courriel', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Courriel')),
            ],
        ),
        migrations.RemoveField(
            model_name='membre',
            name='courriel',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='abonnementatelier',
            name='item_ptr',
            field=models.OneToOneField(default=datetime.datetime(2017, 5, 26, 17, 42, 25, 605394), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item'),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='item_ptr',
            field=models.OneToOneField(default=datetime.datetime(2017, 5, 26, 17, 42, 25, 607818), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item'),
        ),
        migrations.AlterField(
            model_name='contributionvolontaire',
            name='item_ptr',
            field=models.OneToOneField(default=datetime.datetime(2017, 5, 26, 17, 42, 25, 607105), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item'),
        ),
        migrations.AlterField(
            model_name='entreposage',
            name='item_ptr',
            field=models.OneToOneField(default=datetime.datetime(2017, 5, 26, 17, 42, 25, 606301), on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Client'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payee',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
        migrations.AddField(
            model_name='membre',
            name='client_ptr',
            field=models.OneToOneField(auto_created=True, default='roxane.debruyker@gmail.com', on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ventes.Client'),
            preserve_default=False,
        ),
    ]
