# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0025_auto_20170601_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='client_ptr',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ventes.Client'),
        ),
    ]
