# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0026_auto_20170601_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='courriel',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False, verbose_name='Courriel'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='client_ptr',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Client'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='idMembre',
            field=models.CharField(max_length=6, verbose_name='Numéro de membre'),
        ),
    ]
