# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0027_auto_20170601_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benevole',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Client')),
                ('cp', models.CharField(blank=True, max_length=7, verbose_name='Code Postal')),
                ('telephone', models.CharField(blank=True, max_length=12, verbose_name='Numéro de téléphone')),
                ('nbHeuresCum', models.IntegerField(verbose_name="Nombre d'heures de bénévolat cumulées")),
                ('rabaisUtilise', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Prix HT')),
            ],
            bases=('ventes.client',),
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Client')),
                ('cp', models.CharField(blank=True, max_length=7, verbose_name='Code Postal')),
                ('telephone', models.CharField(blank=True, max_length=12, verbose_name='Numéro de téléphone')),
                ('domaine1', models.CharField(choices=[('bois', 'bois'), ('metal', 'metal'), ('securite', 'sécurité'), ('couture', 'couture'), ('tissage', 'tissage'), ('informatique', 'informatique'), ('electronique', 'electronique'), ('art', 'art'), ('soudure', 'soudure'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 1')),
                ('domaine2', models.CharField(choices=[('bois', 'bois'), ('metal', 'metal'), ('securite', 'sécurité'), ('couture', 'couture'), ('tissage', 'tissage'), ('informatique', 'informatique'), ('electronique', 'electronique'), ('art', 'art'), ('soudure', 'soudure'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 2')),
                ('domaine3', models.CharField(choices=[('bois', 'bois'), ('metal', 'metal'), ('securite', 'sécurité'), ('couture', 'couture'), ('tissage', 'tissage'), ('informatique', 'informatique'), ('electronique', 'electronique'), ('art', 'art'), ('soudure', 'soudure'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 3')),
                ('nbHeuresCum', models.IntegerField(verbose_name="Nombre d'heures de bénévolat cumulées")),
                ('rabaisUtilise', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Prix HT')),
                ('desc', models.TextField(verbose_name="Description de l'expérience")),
            ],
            bases=('ventes.client',),
        ),
    ]
