# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0028_benevole_formateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='rabaisUtilise',
        ),
    ]
