# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0029_remove_formateur_rabaisutilise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='cp',
        ),
        migrations.AddField(
            model_name='formateur',
            name='compensationHeure',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='domaine1',
            field=models.CharField(blank=True, choices=[('bois', 'bois'), ('metal', 'metal'), ('securite', 'sécurité'), ('couture', 'couture'), ('tissage', 'tissage'), ('informatique', 'informatique'), ('electronique', 'electronique'), ('art', 'art'), ('soudure', 'soudure'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 1'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='domaine2',
            field=models.CharField(blank=True, choices=[('bois', 'bois'), ('metal', 'metal'), ('securite', 'sécurité'), ('couture', 'couture'), ('tissage', 'tissage'), ('informatique', 'informatique'), ('electronique', 'electronique'), ('art', 'art'), ('soudure', 'soudure'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 2'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='domaine3',
            field=models.CharField(blank=True, choices=[('bois', 'bois'), ('metal', 'metal'), ('securite', 'sécurité'), ('couture', 'couture'), ('tissage', 'tissage'), ('informatique', 'informatique'), ('electronique', 'electronique'), ('art', 'art'), ('soudure', 'soudure'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 3'),
        ),
    ]
