# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0030_auto_20170602_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benevole',
            name='client_ptr',
        ),
        migrations.RemoveField(
            model_name='benevole',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='benevole',
            name='telephone',
        ),
        migrations.AddField(
            model_name='benevole',
            name='membre_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Membre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benevole',
            name='rabaisUtilise',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Rabais Utilisé'),
        ),
    ]
