# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0031_auto_20170602_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='domaine1',
            field=models.CharField(blank=True, choices=[('accueil', 'accueil'), ('informatique', 'informatique'), ('asso', 'asso'), ('communication', 'communication et evenementiel'), ('atelier', 'atelier'), ('admin', 'admin'), ('commercial', 'commercial'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 1'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='domaine2',
            field=models.CharField(blank=True, choices=[('accueil', 'accueil'), ('informatique', 'informatique'), ('asso', 'asso'), ('communication', 'communication et evenementiel'), ('atelier', 'atelier'), ('admin', 'admin'), ('commercial', 'commercial'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 2'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='domaine3',
            field=models.CharField(blank=True, choices=[('accueil', 'accueil'), ('informatique', 'informatique'), ('asso', 'asso'), ('communication', 'communication et evenementiel'), ('atelier', 'atelier'), ('admin', 'admin'), ('commercial', 'commercial'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 3'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='membre_ptr',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Membre'),
        ),
    ]
