# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0033_auto_20170605_1933'),
    ]

    operations = [
        migrations.DeleteModel(name='Formateur')
        ]
