# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0035_formateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benevole',
            name='membre_ptr',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='client_ptr',
        ),
        migrations.AddField(
            model_name='benevole',
            name='membre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ventes.Membre'),
        ),
        migrations.AddField(
            model_name='membre',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ventes.Client'),
        ),
        migrations.AddField(
            model_name='benevole',
            name='numero',
            field=models.CharField(default=1, max_length=6, primary_key=True, serialize=False, verbose_name='Numéro de bénévole'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='idMembre',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Numéro de membre'),
        ),
    ]
