# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0036_auto_20170606_1550'),
    ]

    operations = [
    ]
