# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0038_auto_20170607_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='courriel',
            field=models.EmailField(max_length=50, verbose_name='Courriel'),
        ),

        migrations.AlterField(
            model_name='benevole',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Membre'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Client'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='benevole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventes.Benevole'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Client'),
        ),
        migrations.DeleteModel(name='Benevole'),
        migrations.RemoveField(
            model_name='transaction',
            name='benevole',
        ),
    ]
