# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0039_auto_20170607_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benevole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('nbHeuresCum', models.IntegerField(verbose_name="Nombre d'heures de bénévolat cumulées")),
                ('rabaisUtilise', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Rabais Utilisé')),
                ('domaine1', models.CharField(blank=True, choices=[('accueil', 'accueil'), ('informatique', 'informatique'), ('asso', 'asso'), ('communication', 'communication et evenementiel'), ('atelier', 'atelier'), ('admin', 'admin'), ('commercial', 'commercial'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 1')),
                ('domaine2', models.CharField(blank=True, choices=[('accueil', 'accueil'), ('informatique', 'informatique'), ('asso', 'asso'), ('communication', 'communication et evenementiel'), ('atelier', 'atelier'), ('admin', 'admin'), ('commercial', 'commercial'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 2')),
                ('domaine3', models.CharField(blank=True, choices=[('accueil', 'accueil'), ('informatique', 'informatique'), ('asso', 'asso'), ('communication', 'communication et evenementiel'), ('atelier', 'atelier'), ('admin', 'admin'), ('commercial', 'commercial'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 3')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Membre')),
            ],
        ),
    ]
