# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0039_auto_20170606_1618'),
    ]

    operations = []
