# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0041_auto_20170607_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='benevole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventes.Benevole'),
        ),
    ]
