# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0041_delete_benevole_membre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benevole',
            fields=[
                ('numero', models.CharField(default=1, max_length=6, primary_key=True, serialize=False, verbose_name='Numéro de bénévole')),
                ('nbHeuresCum', models.IntegerField(verbose_name="Nombre d'heures de bénévolat cumulées")),
                ('rabaisUtilise', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Rabais Utilisé')),
                ('domaine1', models.CharField(blank=True, choices=[('accueil', 'accueil'), ('informatique', 'informatique'), ('asso', 'asso'), ('communication', 'communication et evenementiel'), ('atelier', 'atelier'), ('admin', 'admin'), ('commercial', 'commercial'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 1')),
                ('domaine2', models.CharField(blank=True, choices=[('accueil', 'accueil'), ('informatique', 'informatique'), ('asso', 'asso'), ('communication', 'communication et evenementiel'), ('atelier', 'atelier'), ('admin', 'admin'), ('commercial', 'commercial'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 2')),
                ('domaine3', models.CharField(blank=True, choices=[('accueil', 'accueil'), ('informatique', 'informatique'), ('asso', 'asso'), ('communication', 'communication et evenementiel'), ('atelier', 'atelier'), ('admin', 'admin'), ('commercial', 'commercial'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 3')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('idMembre', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Numéro de membre')),
                ('cp', models.CharField(blank=True, max_length=7, verbose_name='Code Postal')),
                ('telephone', models.CharField(blank=True, max_length=12, verbose_name='Numéro de téléphone')),
                ('dateAdh', models.DateField(verbose_name="Date d'Adhésion")),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Client')),
            ],
        ),
        migrations.AddField(
            model_name='benevole',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Membre'),
        ),
    ]
