# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0044_transaction_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commentaire',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
