# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0045_auto_20170607_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='noRef',
            field=models.CharField(max_length=6, verbose_name='Référence Article'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nom',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name="Nom de l'article"),
        ),
    ]
