# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0048_auto_20170608_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliothequeOutils',
            fields=[
                ('duree', models.DurationField(choices=[(datetime.timedelta(7), 'Semaine'), (datetime.timedelta(31), 'Mois'), (datetime.timedelta(365), 'Année')], verbose_name='Durée')),
                ('item_ptr', models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item')),
            ],
            bases=('ventes.item',),
        ),
        migrations.CreateModel(
            name='EspaceE',
            fields=[
                ('duree', models.DurationField(choices=[(datetime.timedelta(7), 'Semaine'), (datetime.timedelta(31), 'Mois'), (datetime.timedelta(365), 'Année')], verbose_name='Durée')),
                ('item_ptr', models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item')),
            ],
            bases=('ventes.item',),
        ),
        migrations.AlterField(
            model_name='formation',
            name='item_ptr',
            field=models.OneToOneField(default=8, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item'),
        ),
    ]
