# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0049_auto_20170608_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatCadeau',
            fields=[
                ('item_ptr', models.OneToOneField(default=8, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item')),
            ],
            bases=('ventes.item',),
        ),
        migrations.AlterField(
            model_name='formation',
            name='item_ptr',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Item'),
        ),
    ]
