# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0052_auto_20170609_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='heure',
            field=models.CharField(default='18h', max_length=5),
        ),
    ]
