# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0053_formation_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='formateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Formateur'),
        ),
    ]
