# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0054_auto_20170609_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
