# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0055_item_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archivé'),
        ),
    ]
