# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0056_auto_20170612_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='noRef',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
