# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0057_auto_20170612_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='compensationHeure',
            field=models.DecimalField(decimal_places=2, default=10.35, max_digits=6, verbose_name="Compensation à l'heure"),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='rabaisUtilise',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Rabais Utilisé'),
        ),
    ]
