# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0058_auto_20170612_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='domaine1',
            field=models.CharField(choices=[('accueil', 'accueil'), ('informatique', 'informatique'), ('asso', 'asso'), ('communication', 'communication et evenementiel'), ('atelier', 'atelier'), ('admin', 'admin'), ('commercial', 'commercial'), ('autre', 'autre')], max_length=15, verbose_name='Domaine 1'),
        ),
    ]
