# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0060_formateur_argentdistribue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='cout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Coût par personne'),
        ),
        migrations.AlterField(
            model_name='item',
            name='prixHT',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix Hors Taxes'),
        ),
        migrations.AlterField(
            model_name='visites',
            name='benevole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.Benevole', verbose_name="Bénévole à l'accueil"),
        ),
    ]
