# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0061_auto_20170614_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='duree',
        ),
        migrations.AddField(
            model_name='formation',
            name='duree_heure',
            field=models.IntegerField(default=2, verbose_name='Durée de la formation en heure'),
        ),
        migrations.AddField(
            model_name='formation',
            name='duree_minute',
            field=models.IntegerField(default=30, verbose_name='Durée de la formation en minute'),
        ),
    ]
