# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0062_auto_20170614_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='duree_minute',
        ),
    ]
