# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0064_formation_duree_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='cout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Coût par personne'),
        ),
    ]
