# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0065_auto_20170614_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='nbHeuresCum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name="Nombre d'heures de formation cumulées"),
        ),
    ]
