# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0066_auto_20170614_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='taxes',
            options={'verbose_name_plural': 'Taxes'},
        ),
        migrations.AlterModelOptions(
            name='visites',
            options={'verbose_name_plural': 'Visites'},
        ),
        migrations.AlterField(
            model_name='benevole',
            name='domaine1',
            field=models.CharField(choices=[('accueil', 'accueil'), ('informatique', 'informatique'), ('asso', 'asso'), ('communication', 'communication et evenementiel'), ('atelier', 'atelier'), ('admin', 'admin'), ('commercial', 'commercial'), ('autre', 'autre')], max_length=15, verbose_name='Fonction principale en tant que bénévole'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='domaine2',
            field=models.CharField(blank=True, choices=[('accueil', 'accueil'), ('informatique', 'informatique'), ('asso', 'asso'), ('communication', 'communication et evenementiel'), ('atelier', 'atelier'), ('admin', 'admin'), ('commercial', 'commercial'), ('autre', 'autre')], max_length=15, null=True, verbose_name='Autre fonction'),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='domaine3',
            field=models.TextField(blank=True, null=True, verbose_name='Intérêts dans la vie'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=30, verbose_name="Nom de famille ou de l'organisation"),
        ),
        migrations.AlterField(
            model_name='formation',
            name='jauge',
            field=models.IntegerField(default=5, verbose_name='Jauge'),
        ),
    ]
