# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0067_auto_20170614_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevole',
            name='disponibilites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benevole',
            name='domaine3',
            field=models.TextField(blank=True, null=True, verbose_name='Intérêts dans la vie/pour la patente'),
        ),
    ]
