# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0068_auto_20170614_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliothequeoutils',
            options={'verbose_name_plural': "Bibliotheque d'outils"},
        ),
        migrations.AlterModelOptions(
            name='certificatcadeau',
            options={'verbose_name_plural': 'Certificats cadeau'},
        ),
        migrations.AlterModelOptions(
            name='contributionvolontaire',
            options={'verbose_name_plural': 'Contributions volontaires'},
        ),
        migrations.AlterModelOptions(
            name='espacee',
            options={'verbose_name_plural': 'Espace E'},
        ),
    ]
