# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0071_auto_20170615_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='domaine',
            field=models.CharField(choices=[('bois', 'bois'), ('metal', 'metal'), ('securite', 'sécurité'), ('couture', 'couture'), ('tissage', 'tissage'), ('informatique', 'informatique'), ('electronique', 'electronique'), ('art', 'art'), ('soudure', 'soudure'), ('autre', 'autre')], default='bois', max_length=15),
        ),
    ]
