# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0074_auto_20170616_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhesion',
            options={'verbose_name_plural': 'Adhésion à la Patente'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': "Tous les items que l'on vend"},
        ),
        migrations.AlterModelOptions(
            name='visites',
            options={'verbose_name_plural': 'Présences'},
        ),
        migrations.AlterField(
            model_name='taxes',
            name='tps',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='tvq',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
