# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0075_auto_20170616_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnementatelier',
            name='duree',
            field=models.DurationField(choices=[(datetime.timedelta(0, 14400), 'Soir'), (datetime.timedelta(1), 'Journée'), (datetime.timedelta(7), 'Semaine'), (datetime.timedelta(31), 'Mois'), (datetime.timedelta(93), '3 Mois'), (datetime.timedelta(186), '6 Mois'), (datetime.timedelta(365), 'Année')], verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='domaine1',
            field=models.CharField(blank=True, choices=[('securte', 'initiation à la Patente'), ('bois', 'bois'), ('metal', 'metal'), ('textile', 'textile'), ('informatique', 'informatique'), ('electronique', 'electronique'), ('divers', 'autre')], max_length=15, verbose_name='Domaine 1'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='domaine2',
            field=models.CharField(blank=True, choices=[('securte', 'initiation à la Patente'), ('bois', 'bois'), ('metal', 'metal'), ('textile', 'textile'), ('informatique', 'informatique'), ('electronique', 'electronique'), ('divers', 'autre')], max_length=15, verbose_name='Domaine 2'),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='domaine3',
            field=models.CharField(blank=True, choices=[('securte', 'initiation à la Patente'), ('bois', 'bois'), ('metal', 'metal'), ('textile', 'textile'), ('informatique', 'informatique'), ('electronique', 'electronique'), ('divers', 'autre')], max_length=15, verbose_name='Domaine 3'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='domaine',
            field=models.CharField(choices=[('bois', 'bois'), ('metal', 'metal'), ('securite', 'sécurité'), ('textile', 'textile'), ('informatique', 'informatique'), ('electronique', 'electronique'), ('divers', 'autre')], default='bois', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='nom',
            field=models.CharField(max_length=41, verbose_name="Nom de l'article"),
        ),
    ]
