# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0031_auto_20170602_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benevole',
            name='membre_ptr',
        ),
        migrations.AddField(
            model_name='benevole',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2017, 6, 2, 18, 59, 47, 408504, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
