# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0033_auto_20170602_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benevole',
            name='id',
        ),
        migrations.AddField(
            model_name='benevole',
            name='membre_ptr',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventes.Membre'),
        ),
    ]
